import type React from "react";

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(160deg, #fdf2f8 0%, #fce7f3 50%, #ede9fe 100%)",
    fontFamily: "'Segoe UI', 'Apple SD Gothic Neo', sans-serif",
  },
  card: {
    background: "rgba(255,255,255,0.85)",
    backdropFilter: "blur(12px)",
    borderRadius: 28,
    padding: "28px 32px 32px",
    width: 300,
    boxShadow: "0 8px 32px rgba(244,114,182,0.18), 0 2px 8px rgba(0,0,0,0.06)",
    border: "1.5px solid rgba(249,168,212,0.4)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
    color: "#be185d",
    letterSpacing: -0.5,
  },
  iconBtn: {
    background: "none",
    border: "none",
    fontSize: 20,
    cursor: "pointer",
    padding: 4,
    borderRadius: 8,
    transition: "transform 0.2s",
  },
  tabs: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    padding: "8px 0",
    borderRadius: 14,
    border: "1.5px solid #fce7f3",
    background: "#fff0f6",
    color: "#9d174d",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  tabActive: {
    background: "linear-gradient(135deg,#fbcfe8,#f9a8d4)",
    border: "1.5px solid #f472b6",
    color: "#831843",
    boxShadow: "0 2px 8px rgba(244,114,182,0.3)",
  },
  circleWrap: {
    display: "flex",
    justifyContent: "center",
    marginBottom: 20,
  },
  controls: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  btnPrimary: {
    flex: 1,
    padding: "13px 0",
    borderRadius: 18,
    border: "none",
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(244,114,182,0.35)",
    transition: "transform 0.1s, box-shadow 0.2s",
    letterSpacing: 0.3,
  },
  btnSecondary: {
    padding: "13px 14px",
    borderRadius: 18,
    border: "1.5px solid #fce7f3",
    background: "#fff0f6",
    fontSize: 18,
    cursor: "pointer",
    transition: "transform 0.1s",
  },
  settings: {
    marginTop: 20,
    padding: "16px",
    background: "#fff8fb",
    borderRadius: 16,
    border: "1.5px solid #fce7f3",
  },
  settingsTitle: {
    margin: "0 0 12px",
    fontSize: 13,
    fontWeight: 700,
    color: "#be185d",
  },
  settingsRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  label: {
    fontSize: 13,
    color: "#6b7280",
    fontWeight: 500,
  },
  stepper: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  stepBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "1.5px solid #fce7f3",
    background: "#fff",
    color: "#be185d",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
  },
  stepVal: {
    fontSize: 13,
    fontWeight: 700,
    color: "#374151",
    minWidth: 32,
    textAlign: "center",
  },
};

export default styles;
