import type React from "react";

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--th-page-bg)",
    fontFamily: "'Segoe UI', 'Apple SD Gothic Neo', sans-serif",
  },
  card: {
    background: "var(--th-card-bg)",
    backdropFilter: "blur(12px)",
    borderRadius: 28,
    padding: "28px 32px 32px",
    boxShadow: "0 8px 32px rgba(var(--th-shadow-rgb), 0.18), 0 2px 8px rgba(0,0,0,0.06)",
    border: "1.5px solid rgba(var(--th-shadow-rgb), 0.3)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
    color: "var(--th-p700)",
    letterSpacing: -0.5,
  },
  iconBtn: {
    background: "none",
    border: "none",
    fontSize: 20,
    cursor: "pointer",
    padding: 4,
    borderRadius: 8,
    transition: "transform 0.2s",
  },
  tabs: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    padding: "8px 0",
    borderRadius: 14,
    border: "1.5px solid var(--th-p100)",
    background: "var(--th-p50)",
    color: "var(--th-p700)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  tabActive: {
    background: "linear-gradient(135deg, var(--th-p200), var(--th-p300))",
    border: "1.5px solid var(--th-p400)",
    color: "var(--th-p800)",
    boxShadow: "0 2px 8px rgba(var(--th-shadow-rgb), 0.3)",
  },
  circleWrap: {
    display: "flex",
    justifyContent: "center",
    marginBottom: 20,
  },
  controls: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  btnPrimary: {
    flex: 1,
    padding: "13px 0",
    borderRadius: 18,
    border: "none",
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(var(--th-shadow-rgb), 0.35)",
    transition: "transform 0.1s, box-shadow 0.2s",
    letterSpacing: 0.3,
  },
  btnSecondary: {
    padding: "13px 14px",
    borderRadius: 18,
    border: "1.5px solid var(--th-p100)",
    background: "var(--th-p50)",
    fontSize: 18,
    cursor: "pointer",
    transition: "transform 0.1s",
  },
  settings: {
    marginTop: 20,
    padding: "16px",
    background: "var(--th-settings-bg)",
    borderRadius: 16,
    border: "1.5px solid var(--th-p100)",
  },
  settingsTitle: {
    margin: "0 0 12px",
    fontSize: 13,
    fontWeight: 700,
    color: "var(--th-p700)",
  },
  settingsRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  label: {
    fontSize: 13,
    color: "var(--th-text-label)",
    fontWeight: 500,
  },
  stepper: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  stepBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "1.5px solid var(--th-p100)",
    background: "var(--th-step-bg)",
    color: "var(--th-p700)",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
  },
  stepVal: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--th-text-val)",
    minWidth: 32,
    textAlign: "center",
  },
  sessionBadge: {
    marginTop: 14,
    textAlign: "center",
    fontSize: 13,
    color: "var(--th-text-label)",
    letterSpacing: 0.2,
  },
  streakBadge: {
    marginTop: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    padding: "7px 14px",
    background: "linear-gradient(135deg, var(--th-p50), var(--th-p100))",
    borderRadius: 20,
    border: "1.5px solid var(--th-p200)",
  },
  streakText: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--th-p700)",
    letterSpacing: -0.2,
  },
};

export default styles;
